### ISSUE TITLE
Brush drawing issue

### ISSUE THREAD

**Issue by ervinod** [burhanrashid52/PhotoEditor#57]
Hello there,
Brush drawing is automatically removed from view when saving image
Please follow following scenario to detect bug:
1. Draw something on screen using brush.
2. Save Image (working correctly as expected)
3. Add Sticker
4. Save Image (working correctly as expected)
5. Draw something on screen using brush
6. Save Image **(Bug)**
In saved image brush drawing that i have drawn on view in step 5 is not reflected. means when i click save button (step 6), the last added view i.e. brush is removed

Please check this issue and solve in next release

**Comment by ervinod** [comment]
Hello there... have you checked this issue

**Comment by ervinod** [comment]
@burhanrashid52 have u checked this issue ?

**Comment by burhanrashid52** [comment]
I was out of station for a week. Let me look into it

**Comment by ervinod** [comment]
@burhanrashid52 Okay... Please check this issue when you get time

**Comment by ervinod** [comment]
@burhanrashid52  hello there..... have you got any solution to resolve this bug ?

**Comment by burhanrashid52** [comment]
No, still I am not able to trace the bug. I am actively working on it. This happens with the brush only. It works fine with sticker and emojis.

**Comment by ervinod** [comment]
Okay..... To resolve this bug i tried to save image in the way that is used in PhotoEditorSDK library , but i am failed to resolve the issue.....

**Comment by tusharSensovium** [comment]
I am also facing the same issue. Any suggestion?

**Comment by qlehong** [comment]
HI @ervinod Could you review and verify this pull request https://github.com/burhanrashid52/PhotoEditor/pull/181
for this bug? Thank you!

**Comment by gurpreetsudan** [comment]
@qlehong thanks it is resolved by this :)

**Comment by Arsikkk98** [comment]
I still have this error, changes from @qlehong have not been saved?
